# Generated by Django 3.1.7 on 2021-06-11 09:26

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210513_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='background_image_alt',
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='store-backgrounds'),
        ),
    ]
