# Generated by Django 3.1.7 on 2021-05-31 04:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_auto_20210529_0401'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
